PROJECT=dap
PROJECT_NAME=dap
PROJECT_VERSION=20140914
PROJECT_EMAIL=jeffk@jdkoftinoff.com
PROJECT_LICENSE=BSD
PROJECT_MAINTAINER=jeffk@jdkoftinoff.com
PROJECT_COPYRIGHT=Copyright 2014
PROJECT_DESCRIPTION=dap
PROJECT_WEBSITE=http://github.com/jdkoftinoff/dap
PROJECT_IDENTIFIER=com.jdkoftinoff.dap
TOP_LIB_DIRS+=.
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=

CXXFLAGS_MACOSX+=-std=c++11 -stdlib=libc++
CXXFLAGS_LINUX+=-std=c++11

